version: '3'
services:
    postgre:
        image: postgres:latest
        ports:
            - 5432:5432
        container_name: my_postgre
        volumes:
        - ./postgres/data:/var/lib/postgresql/data
        # 初期化用のシェルを格納しておきます。
        - ./postgres/setup:/docker-entrypoint-initdb.d
        environment: 
            POSTGRES_USER: misaka
            POSTGRES_PASSWORD: mikoto
