spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/misaka
    username: misaka
    password: mikoto
  messages:
    basename: messages,ValidationMessages
    cache-duration: -1
    encoding: UTF-8
  